In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
arr = np.array([10,20,30,40])
print(arr)

#array type
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [12]:
# types of array

# 1D array
arr1 = np.array([1,2,3,4])
print("1d array:",arr1)

# 2D array
arr2 = np.array([[5,6,7],
                 [8,9,10]])
print(" 2d array :",arr2)

# 3d array
arr3 = np.array([[[9,8,7],
                  [6,5,4],
                  [3,2,1]]])
print(" 3d array :", arr3)

1d array: [1 2 3 4]
 2d array : [[ 5  6  7]
 [ 8  9 10]]
 3d array : [[[9 8 7]
  [6 5 4]
  [3 2 1]]]


In [14]:
# shape of array

arr = np.array([[5,6,7],
                 [8,9,10]])
print(arr.shape)

(2, 3)


In [15]:
# size of array
print(arr.size)

6


In [16]:
# reshapaing array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr =arr.reshape(4,3)
print(new_arr)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
# iterating array element

arr= np.array([1,2,3,4])
for i in arr:
    print(i)

1
2
3
4


In [ ]:
#