In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
arr = np.array([10,20,30,40])
print(arr)

#array type
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [12]:
# types of array

# 1D array
arr1 = np.array([1,2,3,4])
print("1d array:",arr1)

# 2D array
arr2 = np.array([[5,6,7],
                 [8,9,10]])
print(" 2d array :",arr2)

# 3d array
arr3 = np.array([[[9,8,7],
                  [6,5,4],
                  [3,2,1]]])
print(" 3d array :", arr3)

1d array: [1 2 3 4]
 2d array : [[ 5  6  7]
 [ 8  9 10]]
 3d array : [[[9 8 7]
  [6 5 4]
  [3 2 1]]]


In [14]:
# shape of array

arr = np.array([[5,6,7],
                 [8,9,10]])
print(arr.shape)

(2, 3)


In [15]:
# size of array
print(arr.size)

6


In [16]:
# reshapaing array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr =arr.reshape(4,3)
print(new_arr)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
# iterating array element

arr= np.array([1,2,3,4])
for i in arr:
    print(i)

1
2
3
4


In [2]:
#joining array
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
array = np.concatenate([arr1,arr2])
print(array)

[1 2 3 4 5 6]


In [3]:
# spliting array

arr = np.array([1,2,3,4,5,6])
new_arr = np.split(arr,3)
print(new_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [4]:
# searching array

arr = np.array([1,4,2,3,4,5,4,6])
new_arr = np.where(arr==4)
print(new_arr)


(array([1, 4, 6], dtype=int64),)


In [8]:
# sorting array

arr = np.array([3,1,5,6,2])

# ascending order
print(np.sort(arr))

# dscending order
print(np.sort(arr)[: :-1])

[1 2 3 5 6]
[6 5 3 2 1]


In [10]:
# create empty list

arr = np.array([10,20,30,40])
filter_arr = []

# go through each element in array
for element in arr:

    if element >35:
        filter_arr.append(True)

    else:
        filter_arr.append(False)


new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)


[False, False, False, True]
[40]


In [11]:
# converting of datatypes

arr = np.array([1,2,3,4])
print(arr.astype(str))

['1' '2' '3' '4']


In [17]:
#adding and removing element

arr = np.array([1,2,3,4,5])
print("orignal array:",arr)

# appending single element
print(np.append(arr,6))

# appending multiple element
print(np.append(arr,[44,55]))

# inserting specific element
print(np.insert(arr,3,100))

# deleting element
print(np.delete(arr,2))        # using indexing 

orignal array: [1 2 3 4 5]
[1 2 3 4 5 6]
[ 1  2  3  4  5 44 55]
[  1   2   3 100   4   5]
[1 2 4 5]


In [23]:
# aggregate function

arr = np.array([10,20,30,40,50])
print("array :",arr)

#sum
print("sum of array :",np.sum(arr))

#Minimum
print("min value :",np.min(arr))

#maximum
print("max value :",np.max(arr))

#cumulative sum
print("cumsum :",np.cumsum(arr))

array : [10 20 30 40 50]
sum of array : 150
min value : 10
max value : 50
cumsum : [ 10  30  60 100 150]


In [30]:
# statistical function

import statistics as stats

food_prices = [100,200,300,400,500,300,200]
a = np.array(food_prices)

# mean
print("mean :",np.mean(a))

# median
print("median :",np.median(a))

# mode
print("mode :",stats.mode(a))

# SD
print("standard deviation :",np.std(a))

mean : 285.7142857142857
median : 300.0
mode : 200
standard deviation : 124.53996981544782
